export const dataProducts = [
  {
    id: "1",
    name: "Стул «Карамель»",
    newPrice: "$195",
    oldPrice: "$245",
    imgSrc: "./img/chair-caramel-desktop.png",
    alt: "chair",
  },
  {
    id: "2",
    name: "Стул «Облако»",
    newPrice: "$200",
    oldPrice: "$250",
    imgSrc: "./img/chair-cloud-desktop.jpg",
    alt: "chair",
  },
  {
    id: "3",
    name: "Стул «Сова»",
    newPrice: "$240",
    oldPrice: "$260",
    imgSrc: "./img/chair-owl-desktop.png",
    alt: "chair",
  },
  {
    id: "4",
    name: "Стул «Мая»",
    newPrice: "$280",
    oldPrice: "$330",
    imgSrc: "./img/chair-maya-desktop.jpg",
    alt: "chair",
  },
  {
    id: "5",
    name: "Стул «Месси»",
    newPrice: "$280",
    oldPrice: "$305",
    imgSrc: "./img/chair-messi-desktop.png",
    alt: "chair",
  },
  {
    id: "6",
    name: "Стул «Карамель»",
    newPrice: "$195",
    oldPrice: "$245",
    imgSrc: "./img/chair-caramel-desktop.png",
    alt: "chair",
  },
  {
    id: "7",
    name: "Стул «Карамель»",
    newPrice: "$195",
    oldPrice: "$245",
    imgSrc: "./img/chair-caramel-desktop.png",
    alt: "chair",
  },
  {
    id: "8",
    name: "Стул «Карамель»",
    newPrice: "$195",
    oldPrice: "$245",
    imgSrc: "./img/chair-caramel-desktop.png",
    alt: "chair",
  },
  {
    id: "9",
    name: "Стул «Карамель»",
    newPrice: "$195",
    oldPrice: "$245",
    imgSrc: "./img/chair-caramel-desktop.png",
    alt: "chair",
  },
]